.changeset/bright-feet-behave.md, .changeset/bright-tomatoes-juggle.md, libs/ts-rest/core/CHANGELOG.md, libs/ts-rest/core/package.json, libs/ts-rest/express/CHANGELOG.md, libs/ts-rest/express/package.json, libs/ts-rest/nest/CHANGELOG.md, libs/ts-rest/nest/package.json, libs/ts-rest/open-api/CHANGELOG.md, libs/ts-rest/open-api/package.json, libs/ts-rest/react-query/CHANGELOG.md, libs/ts-rest/react-query/package.json
=> Revert "Release Tracking"

.changeset/poor-lamps-wonder.md, libs/ts-rest/express/src/lib/ts-rest-express.ts
=> fix: Missing Zod for express

.changeset/serious-countries-speak.md, .changeset/smart-parents-yell.md, apps/example-express/src/test.http, libs/example-contracts/src/lib/contract-blog.ts, libs/ts-rest/express/src/lib/ts-rest-express.ts
=> Improve express error handling - handle with next(e) rather than custom error message

apps/docs/docs/react-query.md
Hello :)
I just fix 2 typos in the @ts-rest/react-query doc.
Have a nice day
=> Fix typos in react-query doc

.changeset/spotty-cherries-camp.md, README.md, apps/docs/docs/react-query.md, apps/example-next/tests/react-query.spec.tsx, libs/ts-rest/react-query/src/lib/react-query.ts
=> Add useQueries to @tanstack/react-query

libs/ts-rest/core/project.json, libs/ts-rest/express/project.json, libs/ts-rest/nest/project.json, libs/ts-rest/next/project.json, libs/ts-rest/open-api/project.json, libs/ts-rest/react-query/project.json, libs/ts-rest/solid-query/project.json, package.json, pnpm-lock.yaml, tools/scripts/rollup.config.js
merge from my own repo, I forgot I now have branch access 💀
=> fix: cleanup comments, JSDocs, anything else from compiled JS

.changeset/giant-lizards-jam.md, libs/ts-rest/core/src/lib/client.ts, libs/ts-rest/react-query/src/lib/react-query.ts, libs/ts-rest/solid-query/src/lib/solid-query.ts
=> Drop usage of ES6 Proxy

apps/docs/docs/core/fetch.md, apps/example-next/tests/react-query.spec.tsx, libs/ts-rest/core/src/lib/client.spec.ts, libs/ts-rest/core/src/lib/client.ts
Was originally for https://github.com/ts-rest/ts-rest/pull/145
Fixes #141
=> fix: proposed changes on oliver's PR for #141

libs/ts-rest/core/src/lib/client.spec.ts, libs/ts-rest/core/src/lib/client.ts, package.json, pnpm-lock.yaml
Addresses comment on PR https://github.com/ts-rest/ts-rest/pull/147#discussion_r1086165066, fixes #141
=>  fix: revised PR #147

.changeset/hip-peaches-sell.md, libs/ts-rest/core/src/lib/client.ts
=> fix(core/client): wrong content-type detection.

FUNDING.md
Add FUNDING.md, funding will be split across the ts-rest team! Thanks all! ❤️
=> feat: funding readme

apps/docs/docs/express.mdx, apps/docs/docs/guides/without-backend.mdx, apps/docs/docs/nest.mdx, apps/docs/docs/next.mdx, apps/docs/docs/quickstart.mdx, apps/docs/docs/react-query.mdx, apps/docs/src/components/InstallTabs.tsx, libs/ts-rest/express/src/lib/ts-rest-express.ts
Hi All, I really like this project and would love to contribute more to this project. I rarely contribute to an open-source project before. Please let me know if there is any step that I should do first before doing any PR. Such as, should I create an Issue first for this kind of Docs improvement? Thanks.   
Changes:
- Added tabs for popular package manager in the package installation section.
- Also, I fixed a little typescript type warning in `ts-rest-express.ts`.
https://user-images.githubusercontent.com/7936061/216814679-321bbfc2-db85-455d-867a-1e4781ae2963.mov
=> docs: add popular package managers installation

apps/docs/docs/guides/non-ts-clients.mdx, apps/docs/docs/open-api.mdx, apps/docs/docusaurus.config.js, apps/docs/sidebars.js, apps/example-microservice/posts-service/src/main.ts, libs/example-microservice/util-posts-api/src/lib/example-microservice-util-posts-api.ts, libs/ts-rest/core/src/lib/client.ts, libs/ts-rest/open-api/src/lib/ts-rest-open-api.ts
Finally document this lib!!
closes #111
=> feat: document open-api lib

apps/docs/docs/core/custom.md
=> enhance Custom Client example

.changeset/lucky-cats-laugh.md, libs/ts-rest/core/project.json, libs/ts-rest/express/project.json, libs/ts-rest/nest/project.json, libs/ts-rest/next/project.json, libs/ts-rest/open-api/project.json, libs/ts-rest/react-query/project.json, libs/ts-rest/solid-query/project.json, package.json, tools/scripts/fix-esm.mjs
Fixes #188
Tested locally and everything works and addresses the issues outlined in #204
=> fix: node16 esm module resolution

.changeset/tricky-numbers-juggle.md, libs/ts-rest/core/src/lib/zod-utils.spec.ts, libs/ts-rest/core/src/lib/zod-utils.ts
=> fix: zod object detection with nested ZodEffects

.changeset/pink-dogs-kneel.md
I accidentally approved that - whoops
=> chore: fix changeset from major to minor

apps/docs/docs/core/core.md
added docs explaining pathPrefix.
Also added a section to keep all options docs in one place - if you disagree with this I can revert :)
=> Docs: added pathPrefix to docs. also added Options section.

libs/ts-rest/core/src/lib/response-validation-error.ts, libs/ts-rest/core/src/lib/server.ts, libs/ts-rest/express/src/lib/ts-rest-express.spec.ts, libs/ts-rest/express/src/lib/ts-rest-express.ts, libs/ts-rest/fastify/src/lib/ts-rest-fastify.spec.ts, libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts, libs/ts-rest/nest/src/lib/ts-rest.interceptor.ts, libs/ts-rest/next/src/lib/ts-rest-next.spec.ts, libs/ts-rest/next/src/lib/ts-rest-next.ts
=> feat: improve response validation error message

.changeset/fair-taxis-explain.md, libs/ts-rest/nest/src/lib/ts-rest-nest-handler.spec.ts, libs/ts-rest/nest/src/lib/ts-rest-nest-handler.ts, package.json, pnpm-lock.yaml
=> Add `@ts-rest/nest` fastify support

.changeset/swift-ears-greet.md, libs/ts-rest/nest/package.json, libs/ts-rest/nest/src/lib/ts-rest-nest-handler.ts, package.json, pnpm-lock.yaml
=> fix: remove extra peer deps from nest lib

README.md
Hello, I've noticed a minor typo in the README. Aside from that, kudos for the great framework!
=> style(README): typo

apps/docs/docs/nest/nest.mdx
Thank you ts-rest team for this awesome library.
This is just a small readme change for something that had me scratching my head for a second when using the Nest handler.
Super obvious in hindsight but might save a few devs a bit of time who are new to the library!
=> Small Nest readme update

libs/ts-rest/open-api/src/lib/ts-rest-open-api.spec.ts, libs/ts-rest/open-api/src/lib/ts-rest-open-api.ts
Added support for headers in generated OpenAPI spec
=> feat: Support headers in generated spec

.changeset/cyan-peaches-notice.md
@neildobson-au I merged your PR #318  without a changeset - this should generate the release action :)
=> chore: changeset

apps/docs/docs/nest/nest.mdx, apps/docs/docs/quickstart.mdx
Added as a result of chatting with 6e696e6f in Discord
https://discord.com/channels/1055855205960392724/1133666569856241705/1134239759259148289
=> docs: document zod requirement

.changeset/four-days-wonder.md, libs/ts-rest/core/src/lib/client.ts
=> fix: tsRestFetchApi content type parsing

.changeset/mighty-spoons-float.md, libs/ts-rest/fastify/src/lib/ts-rest-fastify.spec.ts, libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts
=> fix: unable to nest fastify route implementations

apps/docs/docs/express/express.mdx, apps/docs/docusaurus.config.js
as per:
https://github.com/ts-rest/ts-rest/blob/74eeee04bd18ae9451b1e6cddb9d005bdb171899/libs/ts-rest/express/src/lib/types.ts#L73-L87
=> docs: fix `validateResponses` -> `responseValidation`, also fix edit link

.github/workflows/prerelease.yml, .github/workflows/release.yml
Same as #370 , but for the release actions.
=> fix: update release actions

.changeset/green-kids-yell.md, libs/ts-rest/core/src/lib/client.spec.ts
=> fix: client.spec test

libs/ts-rest/nest/src/lib/ts-rest-nest-handler.ts
Fix https://github.com/ts-rest/ts-rest/issues/392
=> fix: fastify deprecated routerPath property

.changeset/ninety-coins-hunt.md, libs/ts-rest/nest/src/lib/ts-rest-nest-handler.spec.ts, libs/ts-rest/nest/src/lib/ts-rest-nest-handler.ts
=> fix: new nest.js handlers returning promise to interceptors

.changeset/three-pillows-tan.md, libs/ts-rest/core/src/lib/paths.spec.ts, libs/ts-rest/core/src/lib/paths.ts
=> fix(core): optional url parameters typing without path params

.changeset/brown-cherries-reflect.md, apps/example-express/src/get-post.ts, apps/example-express/src/main.ts, apps/example-fastify/src/get-post.ts, apps/example-fastify/src/main.ts, libs/ts-rest/express/src/lib/ts-rest-express.spec.ts, libs/ts-rest/express/src/lib/ts-rest-express.ts, libs/ts-rest/fastify/src/lib/ts-rest-fastify.spec.ts, libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts, libs/ts-rest/next/src/lib/ts-rest-next.spec.ts, libs/ts-rest/next/src/lib/ts-rest-next.ts
=> feat: add single route implementation helper

.changeset/cuddly-experts-press.md, libs/ts-rest/core/src/lib/client.spec.ts, libs/ts-rest/core/src/lib/dsl.spec.ts, libs/ts-rest/core/src/lib/dsl.ts, libs/ts-rest/core/src/lib/infer-types.ts, libs/ts-rest/core/src/lib/server.ts, libs/ts-rest/core/src/lib/type-utils.ts, libs/ts-rest/express/src/lib/ts-rest-express.spec.ts, libs/ts-rest/express/src/lib/ts-rest-express.ts, libs/ts-rest/fastify/src/lib/ts-rest-fastify.spec.ts, libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts, libs/ts-rest/nest/src/lib/ts-rest-nest-handler.spec.ts, libs/ts-rest/nest/src/lib/ts-rest-nest-handler.ts, libs/ts-rest/nest/src/lib/ts-rest-nest.spec.ts, libs/ts-rest/next/src/lib/ts-rest-next.spec.ts, libs/ts-rest/next/src/lib/ts-rest-next.ts, libs/ts-rest/serverless/src/lib/handlers/ts-rest-fetch.spec.ts, libs/ts-rest/serverless/src/lib/handlers/ts-rest-lambda.spec.ts, libs/ts-rest/serverless/src/lib/router.ts
Resolves #540, resolves #542, resolves #543
=> feat: allow server to send no response body

.changeset/proud-dots-smile.md, libs/ts-rest/fastify/src/lib/ts-rest-fastify.spec.ts, libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts
=> fix(fastify): crashing on malformed request json

.changeset/friendly-toes-travel.md, apps/example-next/app/api/app-router/[...ts-rest]/route.ts, libs/ts-rest/serverless/project.json, libs/ts-rest/serverless/src/lib/handlers/ts-rest-next.ts, libs/ts-rest/serverless/src/next-edge.ts, libs/ts-rest/serverless/src/next.ts, tsconfig.base.json
=> feat(serverless): support for next app router route handlers

.changeset/pretty-shoes-breathe.md, apps/example-next/tests/react-query.spec.tsx, libs/ts-rest/react-query/src/lib/inner-types.ts, libs/ts-rest/react-query/src/lib/types.ts, libs/ts-rest/solid-query/src/lib/solid-query.ts, libs/ts-rest/vue-query/src/lib/common.ts, libs/ts-rest/vue-query/src/lib/use-infinite-query.ts, libs/ts-rest/vue-query/src/lib/use-query.ts, libs/ts-rest/vue-query/src/lib/vue-query.spec.ts
=> fix(query): fix `select` option

.changeset/pretty-spoons-dream.md, libs/ts-rest/core/src/lib/client.spec.ts, libs/ts-rest/core/src/lib/client.ts, libs/ts-rest/core/src/lib/infer-types.spec.ts, libs/ts-rest/core/src/lib/infer-types.ts
Solves https://github.com/ts-rest/ts-rest/issues/571
=> feat(core): support for multipart/form-data file array

.changeset/clever-maps-punch.md, apps/docs/docs/open-api.mdx, libs/ts-rest/open-api/src/lib/ts-rest-open-api.spec.ts, libs/ts-rest/open-api/src/lib/ts-rest-open-api.ts
=> feat(openapi): add `operationMapper` option to extend OpenAPI operations

.changeset/smooth-ants-admire.md, apps/docs/docs/core/server-errors.md, apps/docs/docs/serverless/options.md, libs/ts-rest/core/src/index.ts, libs/ts-rest/core/src/lib/response-error.ts, libs/ts-rest/express/src/lib/ts-rest-express.spec.ts, libs/ts-rest/express/src/lib/ts-rest-express.ts, libs/ts-rest/fastify/src/lib/ts-rest-fastify.spec.ts, libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts, libs/ts-rest/nest/src/lib/ts-rest-nest-handler.ts, libs/ts-rest/nest/src/lib/ts-rest-nest.spec.ts, libs/ts-rest/nest/src/lib/ts-rest.interceptor.ts, libs/ts-rest/next/src/lib/ts-rest-next.spec.ts, libs/ts-rest/next/src/lib/ts-rest-next.ts, libs/ts-rest/serverless/src/lib/handlers/ts-rest-fetch.spec.ts, libs/ts-rest/serverless/src/lib/handlers/ts-rest-lambda.spec.ts, libs/ts-rest/serverless/src/lib/http-error.ts, libs/ts-rest/serverless/src/lib/router.ts
=> feat: `TsRestResponseError` can be thrown from any server package

.changeset/good-apes-study.md, libs/ts-rest/fastify/src/lib/ts-rest-fastify.spec.ts, libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts
=> fix(fastify): fix when nested routers are used with `pathPrefix`

.changeset/sharp-kings-listen.md, libs/ts-rest/core/src/lib/zod-utils.ts, libs/ts-rest/express/src/lib/request-validation-error.ts, libs/ts-rest/express/src/lib/ts-rest-express.spec.ts, libs/ts-rest/fastify/src/lib/ts-rest-fastify.spec.ts, libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts, libs/ts-rest/nest/src/lib/ts-rest-nest-handler.spec.ts, libs/ts-rest/nest/src/lib/ts-rest-nest-handler.ts, libs/ts-rest/next/src/lib/ts-rest-next.spec.ts, libs/ts-rest/next/src/lib/ts-rest-next.ts, libs/ts-rest/serverless/src/lib/handlers/ts-rest-fetch.spec.ts, libs/ts-rest/serverless/src/lib/types.ts
Resolves https://github.com/ts-rest/ts-rest/issues/582
=> feat: export a Zod schema that matches the request validation error responses

apps/docs/docs/serverless/next-serverless.md
i was trying to set it up and got stuck here and took me a while to find out what was wrong since nextjs will just throw a 404 error.
=> update serverless nextjs example for clarity

.changeset/green-readers-change.md, .changeset/spotty-ads-glow.md, .changeset/violet-dogs-explode.md, apps/docs/docs/serverless/routers.md, libs/ts-rest/express/src/lib/ts-rest-express.ts, libs/ts-rest/express/src/lib/types.ts, libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts, libs/ts-rest/next/src/lib/ts-rest-next.ts, libs/ts-rest/react-query/src/lib/react-query.ts, libs/ts-rest/react-query/src/lib/types.ts, libs/ts-rest/serverless/src/aws.ts, libs/ts-rest/serverless/src/azure.ts, libs/ts-rest/serverless/src/fetch.ts, libs/ts-rest/serverless/src/index.ts, libs/ts-rest/serverless/src/lib/handlers/ts-rest-azure-function.ts, libs/ts-rest/serverless/src/lib/handlers/ts-rest-fetch.spec.ts, libs/ts-rest/serverless/src/lib/handlers/ts-rest-fetch.ts, libs/ts-rest/serverless/src/lib/handlers/ts-rest-lambda.ts, libs/ts-rest/serverless/src/lib/handlers/ts-rest-next.ts, libs/ts-rest/serverless/src/lib/router-builder/index.ts, libs/ts-rest/serverless/src/lib/router-builder/router-builder.spec.ts, libs/ts-rest/serverless/src/lib/router-builder/types.ts, libs/ts-rest/serverless/src/lib/router.ts, libs/ts-rest/serverless/src/lib/types.ts, libs/ts-rest/serverless/src/next.ts, libs/ts-rest/solid-query/src/lib/solid-query.ts, libs/ts-rest/vue-query/src/index.ts, libs/ts-rest/vue-query/src/lib/vue-query.ts
=> feat: create fluent router builder for serverless and optimize exported return types

.changeset/friendly-swans-smoke.md, libs/ts-rest/core/src/lib/dsl.spec.ts, libs/ts-rest/core/src/lib/dsl.ts
=> fix(core): fix merging of plain type headers

.changeset/nine-dragons-clap.md, libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts
=> fix(fastify): use fastify logger for route initialization logs

.changeset/late-bugs-destroy.md, libs/ts-rest/core/src/lib/client.spec.ts, libs/ts-rest/core/src/lib/client.ts, libs/ts-rest/core/src/lib/dsl.ts, libs/ts-rest/express/src/lib/ts-rest-express.ts, libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts, libs/ts-rest/open-api/src/lib/ts-rest-open-api.ts, libs/ts-rest/serverless/src/lib/router.ts
=> feat(core): do not require body for DELETE endpoints in contracts

.changeset/serious-fans-run.md, apps/docs/docs/serverless/routers.md, libs/ts-rest/serverless/src/lib/types.ts
=> fix(serverless): revert breaking change from v3.47.0

apps/docs/docs/react-query/v5-setup.mdx
Fixed grammar for readability in v5-setup.mdx
=> [fix/docs]: Grammar update v5-setup.mdx

.github/workflows/build-test.yml, apps/example-azure-function/project.json, apps/example-azure-function/src/functions/index.spec.ts, apps/example-cloudflare-worker/src/index.spec.ts, package.json, pnpm-lock.yaml
Main still flaky ever since to @ts-rest/core
=> fix: kill existing processes on cloudflare port

.changeset/olive-deers-hammer.md, libs/ts-rest/core/src/lib/paths.spec.ts, libs/ts-rest/core/src/lib/paths.ts
=> fix(core): preserve trailing slashes in contract path

.changeset/soft-dolls-leave.md, libs/ts-rest/core/src/lib/client.spec.ts, libs/ts-rest/core/src/lib/client.ts, libs/ts-rest/core/src/lib/paths.spec.ts, libs/ts-rest/core/src/lib/paths.ts
=> fix: url params interpolation with strict check
