ts-rest/ts-rest

.changeset/sweet-trains-cover.md
libs/ts-rest/express/src/lib/ts-rest-express.ts

Allow using both `express()` and `Router()` objects for `createExpressEndpoints`

feat: Make express types less strict

---

apps/docs/docs/quickstart.mdx

According to `initTsRest` is deprecated this PR update quickstart section to use `initContract` insead.

Change `initContract` import in quickstart section

---

.changeset/witty-apricots-exercise.md
apps/docs/docs/core/custom.md
apps/docs/docs/core/fetch.md
apps/docs/sidebars.js
libs/ts-rest/core/src/lib/client.ts

For APIs authenticated using cookies, the cookies are not being sent by default for cross-origin requests, as the default behavior for the fetch API is to use a `same-origin` policy. This means if the API is even on a different subdomain (api.example.com) or a different port, say when running locally, no cookies will be sent. This happens regardless of any CORS headers sent by the backend API.
The only way to solve this problem is to use a custom client using the `api` option, so I've added a `credentials` option that will set the same option on the Fetch API to avoid overriding the client.
I've documented this feature in the docs and added the missing sidebar link to the "custom client" page.

feat: add credentials option for fetch client

---

.changeset/swift-zebras-jam.md
libs/ts-rest/open-api/src/lib/ts-rest-open-api.spec.ts
libs/ts-rest/open-api/src/lib/ts-rest-open-api.ts

Hi again!
Query parameters were missing in generated OpenAPI specs so I've added them. I've also expanded on the unit tests to make sure it tests nested routers and setting tags correctly (i.e., `/posts/:id/comments` should set `tags: ['posts', 'comments']`)
There are different ways to serialize query parameters and OpenAPI can be instructed on how to handle these as outlined [here](https://swagger.io/docs/specification/serialization/#:~:text=values%20get%20prefixed.-,Query%20Parameters,-Query%20parameters%20support), but by default, express.js and the like use the default OpenAPI `style` and `explode` formats to handle arrays and objects so I see no compelling reason to add `style` and `explode` options to `generateOpenApi`.
In the case of nested objects, this is not defined in OpenAPI …

fix: add missing query parameters in OpenAPI

---

.changeset/eleven-roses-know.md
libs/ts-rest/core/src/lib/client.ts
libs/ts-rest/react-query/src/lib/ts-rest-client.ts
libs/ts-rest/solid-query/src/lib/solid-query.ts

For cases where zod input and output types differ such as when using `.default()` or `.transform()`, we need to use the input type on the client-side.
```typescript
const foo = z.object({ bar: z.string().default('bar') });
type input = z.input<typeof foo>; // { bar?: string | undefined }
type output = z.infer<typeof foo>; // { bar: string }
```

fix: use z.input for body and query types on clients

---

.changeset/wise-owls-hunt.md
README.md
libs/ts-rest/react-query/package.json

NX strikes again 😅
Looks like with the update to version 15.3, it started generating the libraries with a different file structure, and it's causing this error `TS7016: Could not find a declaration file for module '@ts-rest/react-query'.`
NX automatically generates this if it is not declared explicitly
```json
{
"module": "./index.js",
"main": "./index.cjs",
"type": "module",
"types": "./src/index.d.ts"
}
```
@ts-rest/react-query is the only package with these paths explicitly declared and became invalid when nx started generating index.d.ts inside ./src/index.d.ts instead of ./index.d.ts

fix: let nx generate correct package.json

---

.changeset/long-snails-hammer.md
libs/ts-rest/open-api/src/lib/ts-rest-open-api.spec.ts
libs/ts-rest/open-api/src/lib/ts-rest-open-api.ts

If the same zod object is used multiple times in the same contract object (query, body or response), it will use a $ref to refer to it's first occurrence. For the example in test code, it would have generated to following JSON schema.
```json
"comments": {
"anyOf": [
{
"items": {
"additionalProperties": false,
"properties": {
"id": {
"type": "number"
},
"title": {
"type": "string"
}
},
"required": [
"id",
"title"
],
"type": "object"
},
"type": "array"
},
{
"items": {
"additionalProperties": false,
"properties": {
"author": {
"type": "string"
},
"id": {
"$ref": "#/definitions/zodObject/properties/comments/anyOf/0/items/properties/id"
},
"title": {
"$ref": "#/definitions/zodObject/properties/comments/anyOf/0/items/properties/title"
}
},
"required": [
"id",
"title",
"author"
],
"type": …
```

fix: don't use $ref in OpenAPI

---

.changeset/swift-points-brush.md
libs/ts-rest/core/src/lib/client.spec.ts
libs/ts-rest/core/src/lib/client.ts
libs/ts-rest/core/src/lib/type-utils.ts
libs/ts-rest/react-query/src/lib/react-query.ts

Looks like a small issue was introduced with the `AreAllPropertiesOptional` change. `query` was resolving to `never` if not all of its options were optional, but also for some reason the typing was still broken even they were all optional.
You can see here, typescript was not complaining at all, despite `null` not being an compatible value.

Fix typing for query

---

.changeset/hot-wasps-cry.md
apps/docs/docs/core/core.md
apps/docs/docs/nest.md
apps/example-nest/src/app/post.controller.withResponseShapes.spec.ts
apps/example-nest/src/app/post.controller.withResponseShapes.ts
libs/ts-rest/core/src/lib/client.ts
libs/ts-rest/nest/src/lib/ts-rest-nest.ts

Per discussion on Discord, this feature allows users to extract response types from a given Contract. This is particularly useful for backend services where you want to avoid implementing an interface. 
I aimed to make this as non-intrusive as possible! All tests pass. Please read the modified Docs to get a feel for the changes/additions, and then you can look at `client.ts` to see the entry point of the implementation. 
Here's a screenshot of how it works:

feat: add response shape feature, update docs

---

.changeset/silly-cameras-confess.md
apps/docs/docs/core/core.md
apps/docs/docs/core/fetch.md
apps/docs/docs/express.md
apps/docs/docs/nest.md
apps/docs/docs/next.md
apps/docs/docs/react-query.md
apps/example-express/src/main.ts
apps/example-express/src/tests/ts-posts.spec.ts
apps/example-express/src/ts-router.ts
apps/example-nest/src/app/app.module.ts
apps/example-nest/src/app/post-json-query.controller.ts
apps/example-nest/src/app/post-json-query.spec.ts
apps/example-nest/src/app/post.controller.spec.ts
libs/example-contracts/src/lib/contract-ts.ts
libs/ts-rest/core/src/lib/client.spec.ts
libs/ts-rest/core/src/lib/client.ts
libs/ts-rest/core/src/lib/query.spec.ts
libs/ts-rest/core/src/lib/query.ts
libs/ts-rest/express/src/lib/ts-rest-express.ts
libs/ts-rest/nest/src/index.ts
libs/ts-rest/nest/src/lib/api.decorator.ts
libs/ts-rest/nest/src/lib/json-query.decorator.ts
libs/ts-rest/next/src/lib/ts-rest-next.spec.ts
libs/ts-rest/next/src/lib/ts-rest-next.ts
libs/ts-rest/open-api/src/lib/ts-rest-open-api.spec.ts
libs/ts-rest/open-api/src/lib/ts-rest-open-api.ts
libs/ts-rest/react-query/src/lib/react-query.ts
libs/ts-rest/solid-query/src/lib/solid-query.ts

Now the library can truly claim to offer "Fully typed RPC-like client"
I think the main point of discussion would be the opinionated approach of the selective encoding format of root-level strings.
The implementation, as is, will not JSON encode (i.e. surround with double quotes) a root-level string unless it clashes with a JSON reserved word or is a number.
```typescript
const query = { foo: 'foo', nested: { bar: 'bar' }  };
// ?foo=foo&nested={"bar":"bar"}
const query = { foo: 'true' };
// ?foo="true"
const query = { foo: true };
// ?foo=true
const query = { foo: '123' };
// ?foo="123"
const query = { foo: 123 };
// ?foo=123
```
I think it's nice because this leaves the URL looking like regular query strings in the majority of use cases. This is also how swagger encodes root-level …

Optional JSON-encoded query parameters

---

.github/workflows/release.yml
package.json

Not creating a new release this time so we don't keep releasing unnecessary extra versions. Should go out with next release.

fix: copy README.md after building during release.yml

---

libs/ts-rest/core/project.json
libs/ts-rest/express/project.json
libs/ts-rest/nest/project.json
libs/ts-rest/next/project.json
libs/ts-rest/open-api/project.json
libs/ts-rest/react-query/project.json
libs/ts-rest/solid-query/project.json
package.json
pnpm-lock.yaml
tools/scripts/rollup.config.js

- fix: cleanup comments, JSDocs, anything else from compiled JS
- blank commit
Comments, JSDoc comments, etc, are currently output in the `rollup` compilation jS. This leads to an unnecessary package size increase. Here are some examples from @oliverbutler 
To clean up the comments, the solution is to utilize [rollup-plugin-cleanup](https://github.com/aMarCruz/rollup-plugin-cleanup). Borrowed the Nx strategy from this thread: https://github.com/nrwl/nx/issues/2212#issuecomment-894064983
Note: `rollup` was installed to have the types for `rollup.config.js`.

fix: cleanup compile output

---

.changeset/popular-bikes-greet.md
libs/example-contracts/src/lib/contract-ts.ts
libs/ts-rest/core/src/lib/dsl.ts
libs/ts-rest/core/src/lib/type-utils.spec.ts
libs/ts-rest/core/src/lib/type-utils.ts
libs/ts-rest/express/src/lib/ts-rest-express.spec.ts
libs/ts-rest/express/src/lib/ts-rest-express.ts

feat: enable nested routers by introducing RecursivelyProcessAppRouter

---

.changeset/dull-maps-draw.md
README.md
apps/docs/docs/core/form-data.mdx
apps/docs/docs/nest.md
apps/docs/docs/quickstart.mdx
apps/example-microservice/users-service/src/app/app.controller.ts
apps/example-nest/src/app/post-json-query.controller.ts
apps/example-nest/src/app/post.controller.ts
apps/example-nest/src/app/post.controller.withResponseShapes.ts
libs/ts-rest/core/src/lib/zod-utils.ts
libs/ts-rest/nest/src/index.ts
libs/ts-rest/nest/src/lib/json-query.decorator.ts
libs/ts-rest/nest/src/lib/ts-rest-nest.ts
libs/ts-rest/nest/src/lib/ts-rest-request.decorator.ts
libs/ts-rest/nest/src/lib/ts-rest.interceptor.ts
libs/ts-rest/nest/src/lib/typed-request.decorator.ts

I've renamed some of the Nest function and type names as they have confused some people.
I've also changed how the types are consumed rather than using the `{} as T` hack. In my opinion, this makes it clearer that we are providing types rather than running any significant code at runtime.
Also updated the docs to better explain the role of every function and decorator, and how the type safety is done.
Also fixes #122

Revised Nest function and type names

---

apps/docs/docs/react-query.md

Hi, thanks for the awesome library!
I just tried it out with next.js as a backend implementation. While I was reading the doc, I found that there is a wrong package name in the documentation. I realized it when I try to install it and it is not found. Turns out the right package name was the one in the sidebar. So, I want to contribute a little to fix the doc.
Thanks

Fix incorrect @ts-react/react-query package name in docs

---

.changeset/fresh-dodos-try.md
libs/ts-rest/nest/src/lib/ts-rest.decorator.ts

Pretty neat little method to do "overloads" for arrow functions. This prevents the method decorator signature from being used on classes and vice-versa.

refactor: type safe TsRest decorator

---

.changeset/nine-wasps-flash.md
libs/ts-rest/core/src/lib/client.ts
libs/ts-rest/express/src/lib/ts-rest-express.ts

According to [RFC 2616](https://www.rfc-editor.org/rfc/rfc2616#section-7.2.1) a response _SHOULD_, but not _MUST_, include a content-type header. There are cases where a content-type header is not required such as when returning an empty response. This is common for some DELETE endpoints that return a `204 No Content` response.
I think in this case, returning a blob is appropriate and let the developers handle it how they please

fix: do not throw error for missing content-type header

---

.changeset/calm-bananas-guess.md
.changeset/clean-dots-relate.md
.changeset/early-pillows-train.md
.changeset/gorgeous-crews-scream.md
.changeset/pretty-books-marry.md
.changeset/spicy-kiwis-teach.md
README.md
apps/docs/docs/core/custom.md
apps/docs/docs/core/fetch.md
apps/docs/docs/intro.md
apps/docs/docs/quickstart.mdx
apps/docs/src/pages/index.tsx
apps/example-microservice/web-app-solid/src/App.tsx
apps/example-next/tests/react-query.spec.tsx
libs/ts-rest/core/src/lib/client.spec.ts
libs/ts-rest/core/src/lib/client.ts
libs/ts-rest/core/src/lib/dsl.spec.ts
libs/ts-rest/core/src/lib/test-helpers.ts
libs/ts-rest/core/src/lib/type-utils.spec.ts
libs/ts-rest/core/src/lib/type-utils.ts
libs/ts-rest/react-query/src/lib/react-query.ts
libs/ts-rest/solid-query/src/lib/solid-query.ts
package.json
pnpm-lock.yaml

An action-packed PR! 
- Allow API client args to be set in the custom API fetcher
- Allow headers to be overridden
- Prettify query args (thanks @mattpocock)

Allow extra API client args, allow headers, and prettify query args

---

.changeset/young-wombats-confess.md
libs/ts-rest/core/src/lib/client.spec.ts
libs/ts-rest/core/src/lib/type-utils.spec.ts
libs/ts-rest/core/src/lib/type-utils.ts

Fixes this issue where args was optional despite some args being required

fix: broken typing for optional arguments

---

libs/ts-rest/core/src/lib/client.ts

The getRouteResponses method was removed (mistakenly?), but provides a nice utility function for the client to access response types. The method is still documented here https://ts-rest.com/docs/core/#response-types

fix: restore getRouteResponses method

---

.changeset/purple-comics-notice.md
apps/docs/docs/core/core.md
apps/docs/docs/core/form-data.mdx
apps/docs/docs/core/infer-types.md
apps/docs/sidebars.js
libs/ts-rest/core/src/index.ts
libs/ts-rest/core/src/lib/client.ts
libs/ts-rest/core/src/lib/infer-types.spec.ts
libs/ts-rest/core/src/lib/infer-types.ts

Addressing the issues raised in #192 with the extra added benefit of being able to handle nested contracts.
Given some extra scrutiny, this code can be used to deduplicate a lot of code in the client libraries and also the server libraries.

feat: add type inference helpers

---

apps/docs/docs/core/custom.md
apps/example-next/tests/react-query.spec.tsx
libs/ts-rest/core/src/lib/client.ts

This aims to partially fix #198. 
My coworker discovered this issue when working with API Gateway/AWS Amplify. We have to do the following custom logic when using a Custom Client:
```typescript
// Convert body back to JSON before sending. Right now ts-rest will always stringify the body.
// This causes issue when deployed with API Gateway as API Gateway will also stringify the body.
result = await this.api.post(appConfig.APP_BASENAME, path, { body: JSON.parse(body as string), response: true })
```
The above means the ts-rest custom client stringifies the body, and then we have to _parse_ that stringified body for it to be _re-stringified_ again. This is a big no-no when it comes to performance. 
This PR adds `rawBody` and `contentType` to the params passed to the Custom Client. I know we …

Add rawBody and contentType to Custom Client API arguments

---

.changeset/moody-years-fail.md
libs/ts-rest/core/project.json
libs/ts-rest/express/project.json
libs/ts-rest/nest/project.json
libs/ts-rest/next/project.json
libs/ts-rest/open-api/project.json
libs/ts-rest/react-query/project.json
libs/ts-rest/solid-query/project.json

Fixes #188 
NX was adding `"type": "module"` to the compiled package.json files because we compile `esm` format JS files. This package.json field makes the Typescript compiler of consuming code think that ts-rest libraries are native ES modules, which in fact they are not. We compile both ESM and CJS JS files, but the compiled .d.ts files are in CJS format only, so it needs to be indicated correctly which format the project originally is, so Typescript knows how to transpile our definition files.

fix: compatibility with Node.js TS native ES modules

---

.changeset/pretty-cows-shave.md
libs/ts-rest/core/src/lib/query.spec.ts
libs/ts-rest/core/src/lib/query.ts

If undefined values are present they are converted into the string `undefined`. This is not a valid JSON value so it fails parsing at [parseJsonQueryObject](https://github.com/ts-rest/ts-rest/blob/8011ec7c3cf098570d9f266a4f4cde4a36e38f82/libs/ts-rest/core/src/lib/query.ts#L104).
Filtering it out on the client side means that it will still have the value of undefined on the server.
P.S Thanks for a great library!!

Filter out undefined values from json queries

---

.changeset/stupid-donkeys-flash.md
libs/ts-rest/open-api/src/lib/ts-rest-open-api.spec.ts
libs/ts-rest/open-api/src/lib/ts-rest-open-api.ts

This was missing and threw and error if you tried to instantiate a schema with a refined object at the top level!

feat: OpenAPI support Zod Refine

---

.changeset/wise-pumas-kick.md
libs/ts-rest/core/src/index.ts
libs/ts-rest/core/src/lib/client.spec.ts
libs/ts-rest/core/src/lib/client.ts
libs/ts-rest/core/src/lib/unknown-status-error.ts

Resolves #220
This PR adds a `strict` mode to the client which causes the client to throw errors for any HTTP status returned by the server  which is not defined in the contract.

Implement strict mode to throw on unexpected responses

---

.github/workflows/release.yml
libs/ts-rest/core/project.json
libs/ts-rest/express/project.json
libs/ts-rest/nest/project.json
libs/ts-rest/next/project.json
libs/ts-rest/open-api/project.json
libs/ts-rest/react-query/project.json
libs/ts-rest/solid-query/project.json
package.json

Using the "dotansimha/changesets-action" fork of "changesets/action" which allows us to create a single release for all packages together. Should be better than creating a release per package. Separate tags per package will still be created. This might fix the problem with releases not being created. 
Also cleaned up anything that has to do with `nx_affected` in the release since that was only used previously to determine whether to release docs or not. Vercel now takes care of that, so it is not needed.

chore: use aggregate release for all packages

---

.changeset/happy-hairs-press.md
apps/docs/docs/core/custom.md
apps/docs/docs/core/fetch.md
apps/example-next/tests/react-query.spec.tsx
libs/ts-rest/core/src/lib/client.spec.ts
libs/ts-rest/core/src/lib/client.ts
libs/ts-rest/react-query/src/lib/types.ts
libs/ts-rest/solid-query/src/lib/solid-query.ts

This pull request addresses the enhancement issue #221, wherein we aim to expose response headers to the clients. This could be a breaking change for those using custom API fetchers but will offer a significant improvement in functionality.
Changes:
- The headers have been added to the client fetcher return type in ApiFetcher.
- Added header to both React query and core client
- Updated test fixtures
Notes:
This change may fail type-checking/compiling, but it will not cause any runtime errors as no one would be consuming the non-existent headers. The fix is simple and straightforward. This update prioritizes long-term utility and clarity over short-term compatibility, and we believe it will be greatly beneficial in the long run.
Please review and provide feedback.
/cc @Gabrola, …

feat: exposed response headers to clients

---

libs/ts-rest/nest/src/lib/ts-rest-nest.spec.ts
libs/ts-rest/nest/src/lib/ts-rest-nest.ts

Couple of changes following up on #233
- Passes through AppRoute to ApiRouteServerResponse type correctly
- Undoes change to NestResponseShapes which made return types a promise. This makes requires consumers to wrap the type in `Awaited` to be able to use it.

Fix nest response shape typing

---

.changeset/moody-falcons-confess.md
libs/ts-rest/core/project.json
libs/ts-rest/express/project.json
libs/ts-rest/fastify/project.json
libs/ts-rest/nest/project.json
libs/ts-rest/next/project.json
libs/ts-rest/open-api/project.json
libs/ts-rest/react-query/project.json
libs/ts-rest/solid-query/project.json
tools/scripts/fix-esm.mjs

Trying to upgrade from 3.22 to 3.25 I am getting the following error:
```
const exports = origRequire.apply(this, arguments)
^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/maxbrosnahan/project/node_modules/@ts-rest/nest/index.js from /Users/maxbrosnahan/project/dist/main.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/maxbrosnahan/project/node_modules/@ts-rest/nest/package.json to treat all .js files as CommonJS (using .mjs for all ES …
```

Fix cjs usage of libraries

---

apps/docs/docs/nest.mdx

In Nest, global prefix, versioning, or controller prefixes provide options for adding prefixes to paths in your APIs which we do not support.
Previously, there was a warning stating:
'Currently any existing Nest global prefix, versioning, or controller prefixes will be ignored, please see https://github.com/ts-rest/ts-rest/issues/70 for more details.
Currently, the path in your contract must be the **full path**. Your client may specify a different base URL with a prefix, but this cannot be done at the contract level currently.'
However, we have now introduced the ability to add path prefixes. This serves as a workaround for this missing functionality.
I have updated the documentation to reflect this change:
'Currently any existing Nest global prefix, versioning, or controller prefixes …

Docs: updated warning as of pathPrefix implementation

---

apps/docs/docs/react-query.mdx

Add peer dependency to install command to avoid issues when adopting the @ts-rest/react-query lib.
This should simplify the process for new comers.

add @tanstack/react-query as a package to install alongside with @ts-rest/react-query

---

.changeset/big-colts-carry.md
libs/ts-rest/express/src/index.ts

- resolves #312 
exposed useful internal types like `AppRouteOptions`.
```ts
import { AppRouteOptions } from '@ts-rest/express'
export type HandlerFor<T extends AppRoute> = AppRouteOptions<T>['handler']
// ...
type PatchDeps = Pick<ReviewsService, 'patchReviews'>
type MkPatch = (deps: PatchDeps) => HandlerFor<typeof contract.reviews.patch>
export const mkPatchReviews: MkPatch =
({ patchReviews }) =>
async ({ params: { reviewsId }, req: { user } }) => {
const { id: userId } = getUser.parse(user)
const result = await patchReviews({ reviewsId, userId })
return match(result)
.with(P.instanceOf(ReviewNotFoundError), () => reviewNotFound)
.otherwise(() => ({ status: 200, body: '리뷰 공개 여부가 업데이트되었습니다.' } as const))
}
// ...
const postHandler = mkPostReviews({ createReviews })
export const reviews …
```

feat: expose internal types for @ts-rest/express

---

.changeset/khaki-mugs-poke.md
libs/ts-rest/core/package.json
libs/ts-rest/express/package.json
libs/ts-rest/fastify/package.json
libs/ts-rest/nest/package.json
libs/ts-rest/next/package.json
libs/ts-rest/open-api/package.json
libs/ts-rest/react-query/package.json
libs/ts-rest/solid-query/package.json
package.json
pnpm-lock.yaml

Zod version `3.20.x` causes Typescript IntelliSense slow. Zod itself officially tell us that the version `3.20.x` has compiler problem due to type recursion. You can read for more detail here https://github.com/colinhacks/zod/releases/tag/v3.21.0
- Bump Zod's version to `3.21.4` which is the latest version for all ts-rest libraries 
- Bump @anatine/zod-openapi' version to `2.0.1` which uses zod `3.21.4` as a dependencies
- `ts-rest`'s Typescript should not be slow

Upgrade zod to 3.21.4

---

.changeset/late-panthers-pump.md
libs/ts-rest/fastify/src/lib/ts-rest-fastify.spec.ts
libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts

`requestValidationErrorHandler` currently only handles `RequestValidationError` while silently consuming all other errors. This means that if there is any unhandled error in a route handler, the request never completes.
I added a test case for demonstration, and fixed the issue by re-throwing errors other than `RequestValidationError`.

fix: return errors from fastify route handlers

---

.changeset/light-hotels-think.md
libs/ts-rest/fastify/src/lib/ts-rest-fastify.spec.ts
libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts

`@ts-rest/fastify` currently passes the original request body to the route handler, not the one parsed by zod.
This breaks some zod features that change the output, such as
- [Default values](https://zod.dev/?id=default)
- [Primitive coercion](https://zod.dev/?id=coercion-for-primitives)
- [Transform](https://zod.dev/?id=transform)
- [Preprocess](https://zod.dev/?id=preprocess)
- Stripping unknown fields
This PR fixes that by passing the parsed request body to the route handler instead, like `@ts-rest/express`.

fix(ts-rest-fastify): fix request body validation

---

.changeset/new-kids-add.md
libs/ts-rest/open-api/src/lib/ts-rest-open-api.spec.ts
libs/ts-rest/open-api/src/lib/ts-rest-open-api.ts

Move `"description"` out of `"schema"` as per OpenAPI spec: https://spec.openapis.org/oas/v3.1.0#parameter-object
Fixes #305

fix(ts-rest-open-api): pathParams and query descriptions from `zod` `.describe()`

---

apps/docs/docs/fastify/openapi.mdx

This PR update the fastify swagger integration in openapi guide.
The previous implementation using the `swagger` option can not load descriptions or schemas from the @ts-rest/open-api generated document.
[Preview](https://stackblitz.com/edit/ts-rest-fastify-oas?file=index.js)

docs: update `swagger` to `transformObject`

---

.github/workflows/build-test.yml
package.json
test-projects/nest-10/package.json
test-projects/nest-9/package.json
test-projects/next-app-dir/package.json

Our ci is failing with the following error:
```txt
Running pnpm install --frozen-lockfile
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)
Your pnpm version is incompatible with "/home/runner/work/ts-rest/ts-rest".
Expected version: 8.6
Got: 8.7.0
This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.
To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
Your Node version is incompatible with "/home/runner/work/ts-rest/ts-rest".
Expected version: 18.16
Got: v18.17.1
This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
``` …

fix: fix CI by updating package.json engines

---

.changeset/late-dingos-search.md
libs/ts-rest/express/src/lib/types.spec.ts
libs/ts-rest/express/src/lib/types.ts

This PR adds better type inference for the `req` object of route implementations when using `@ts-rest/express`.
Consider this minimal example, modified from here
https://github.com/tefkah/ts-rest/blob/2073f362cbb1eb35a8bd06e65f36494dc2d8ed8c/libs/ts-rest/express/src/lib/ts-rest-express.spec.ts#L99-L104
Before this PR, after adding `req` to the destructuring argument like so 
```ts
postIndex: async ({ body: { echoHtml }, req }) => {
```
it would have type `any`
```ts
postIndex: async ({ body: { echoHtml }, req }) => {
const body = req.body
//  ^? const body: any
```
After this PR, it will have type `{ echoHtml: string }`, i.e.
```ts
postIndex: async ({ body: { echoHtml }, req }) => {
const body = req.body
//  ^? const body: { echoHtml: string }
```						
Also `req.headers`, `req.query`, …

feat: add better typing for TsRestRequest

---

package.json
pnpm-lock.yaml

For some reason, any version of `@nx/rollup` higher than 16.5.5 seems to break our CI by outputting compiled files as `cjs` instead of `js`. 
This is a temporary workaround to unblock releases until a long term strategy is figured out. 
https://github.com/nrwl/nx/issues/18912

fix: release action fix by reverting to older @nx/rollup version

---

.changeset/afraid-eagles-report.md
apps/docs/docs/core/core.md
libs/ts-rest/core/src/lib/client.ts
libs/ts-rest/core/src/lib/dsl.ts

Addresses #306.
I'm not sure how you'd want testing to be approached for this, as such it's being left open-ended.
The current test suite run using `pnpm build-test-all` executes all the tests successfully.
Overview of changes: 
* Added an optional `boolean` field named `validateResponseOnClient` to the `AppRouteCommon` and `RouterOptions` interfaces to allow for conditional route or router-based response validation.
* Changed the type of `z.ZodTypeAny` to `z.ZodSchema` on `ContactAnyType`.
* Added runtime validation for `application/json` responses to the `tsRestFetchApi`.

feat: add response validation to the client

---

.changeset/great-clouds-teach.md
libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts

Spotted using on a fastify app

fix: remove console log from fastify route initialization

---

.changeset/popular-ants-relax.md
apps/example-next/tests/react-query.spec.tsx
libs/ts-rest/core/src/lib/client.spec.ts
libs/ts-rest/core/src/lib/client.ts
libs/ts-rest/core/src/lib/fetch.spec.ts
libs/ts-rest/next/src/lib/next-client.spec.ts
libs/ts-rest/vue-query/src/lib/vue-query.spec.ts

fixes #383 
Please review: According to [this thread](https://stackoverflow.com/questions/5661596/do-i-need-a-content-type-header-for-http-get-requests), for specifying `content-type: application/json` should be _optional_ for GET requests. 
Will this be ok so long as we correctly communicate this change?

fix: content-type application/json behavior for client

---

apps/docs/docs/quickstart.mdx

Properties in an object should be comma-separated, here one comma is missing, leading to an error.
I add a comma to fix the error.

Fix error due missing comma

---

libs/ts-rest/core/src/lib/client.spec.ts
libs/ts-rest/core/src/lib/client.ts

Fixes #418.
Parse any "text/" content-type with text().

fix: content-type text/html string body (#418)

---

libs/ts-rest/open-api/src/lib/ts-rest-open-api.spec.ts
libs/ts-rest/open-api/src/lib/ts-rest-open-api.ts

Ran into this today, seems like this would be expected behaviour?
also updated the usage of `c.response` as its deprecated.

[OPEN-API] Pass through `contentType` to OpenApi schema

---

apps/docs/docs/quickstart.mdx

Noticed a small variable name mismatch while reading the docs.

fix: Fix variable name mismatch in docs code snippet

---

.changeset/five-singers-jog.md
libs/ts-rest/react-query/package.json
libs/ts-rest/react-query/src/lib/react-query.ts
libs/ts-rest/vue-query/package.json
pnpm-lock.yaml

relates to #415 
This PR establishes compatibility with TanStack Query v5 by using object-syntax internally. 
The external API of @ts-rest/react-query remains unchanged.
Compatibility with v4 remains unchanged.
It prevents React from throwing a runtime error on app launch.
It does **not** implement a full migration to v5 but lays the groundwork to get the ball rolling and apps running again.
Since this is not a fully featured migration I marked it as a patch.

feat: add initial compatibility with react-query v5

---

.changeset/metal-mugs-smoke.md
libs/ts-rest/nest/src/lib/ts-rest-nest-handler.spec.ts
libs/ts-rest/nest/src/lib/ts-rest-nest-handler.ts

Adds support for an optional `HttpExceptionOptions` argument available on the base class `HttpException` from NestJS
Allows developers to include additional context i.e. a root cause error in `TsRestException`, which can be useful in exception filters to centrally catch and log exceptions

feat(ts-rest/nest): http exception options in TsRestException

---

.changeset/purple-rules-shake.md
apps/docs/docs/next.mdx
libs/ts-rest/next/src/lib/ts-rest-next.spec.ts
libs/ts-rest/next/src/lib/ts-rest-next.ts

Adds the ability to throw a `RequestValidationError` for  `@ts-rest/next` (described in #443)
I wanted to customize the response when Zod request validation fails. This allows you to enable throwing a `RequestValidationError` which can then be handled by `errorHandler`. Uses the same `RequestValidationError` that exists within @ts-rest/(express, fastify, nest)

feat: Allow Next.js request validation through error handler

---

.changeset/funny-taxis-brush.md
libs/ts-rest/nest/src/lib/ts-rest-nest-handler.spec.ts
libs/ts-rest/nest/src/lib/ts-rest-nest-handler.ts

* Currently when a `TsRestExceptionFilter` is thrown from a controller, these cannot be caught in a nestjs exception filter. They are instead mapped directly to a response by the `TsRestHandlerInterceptor`
* This change now catches `TsRestExceptionFilter` and re-throws as a nestjs `HttpException`, mapping the response status/body from the original error and nesting it as a cause
This should be a backwards compatible change
* The body/status from a `HttpException` are mapped to the response by default with NestJS, which is what the ts-rest interceptor was doing originally
* We still maintain existing behaviour around response validation
Related issue - https://github.com/ts-rest/ts-rest/issues/450

feat(ts-rest/nest): allow TsRestException to be handled in Nest exception filters

---

.changeset/orange-llamas-battle.md
libs/ts-rest/next/package.json
pnpm-lock.yaml

aims to partially close #428 
- note: this is not to implement things like server actions/next13 route handlers/server components. This is just to get our foot through the door.

feat: allow nextjs14 as a peer dependency

---

.changeset/thin-numbers-taste.md
libs/ts-rest/core/src/lib/client.spec.ts
libs/ts-rest/core/src/lib/client.ts
libs/ts-rest/core/src/lib/dsl.ts

This pull request aims to support `application/x-www-form-urlencoded` `content-type`. Currently it's unsupported and attempting to use the correct headers causes issues. Closes #453

feat(core): Support application/x-www-form-urlencoded content type

---

apps/docs/docs/fastify/fastify.mdx
apps/docs/docs/next.mdx

Fix a couple of small mistakes I found with the documentation.
The error you get with the Fastify example right now:
I have updated the example to import Fastify the way they import it in "Quick Start" example on https://fastify.dev.
Looks like a great project! Can't wait to try it out more!

Small corrections to documentation

---

apps/docs/docs/guides/fake-apis.mdx
apps/docs/sidebars.js

This PR adds a new page to the "Guides" section, detailing how ts-rest can be used to create a fake API for testing purposes.

docs: add fake api guide

---

apps/docs/docs/next.mdx
apps/docs/docs/quickstart.mdx

I haven't used ts-rest yet but when evaluating whether it would be a good fit I was confused by where `initServer` and `api` were coming from.
This commit renames `api` to `contract` for next.js to be consistent with the other library usages and adds a couple comments on where it comes from.
It also adds the import of initServer in the quick start so it's clear that's something ts-rest provides.
--
I haven't actually used ts-rest yet, so please let me know if this commit is wrong.

Use consistent naming in documentation and show dependencies

---

libs/ts-rest/open-api/src/lib/ts-rest-open-api.spec.ts
libs/ts-rest/open-api/src/lib/ts-rest-open-api.ts

Correctly add `style: deepObject` for optional objects

---

.changeset/lovely-snails-divide.md
libs/ts-rest/core/src/lib/client.spec.ts
libs/ts-rest/core/src/lib/client.ts

fix(core): ts-rest overwriting a supplied content-type header

---

.changeset/red-poems-guess.md
libs/ts-rest/core/src/lib/infer-types.spec.ts
libs/ts-rest/core/src/lib/infer-types.ts

fix(core): invalid `extraHeaders` type when no headers are defined in the contract

---

.changeset/long-colts-switch.md
libs/ts-rest/core/src/lib/infer-types.ts

fix(core): broken `params` when `pathParams` is missing and zod is not installed

---

.changeset/wild-penguins-reflect.md
libs/ts-rest/serverless/src/lib/handlers/ts-rest-next.ts

Hello, thanks for the [awesome release](https://github.com/ts-rest/ts-rest/releases/tag/v3.40.0) that adds support to Next App Router.
Everything works great but what I would like to achieve is to have multiple routers and merge them together as I instantiate the handler. I have noticed that the [serverless package does not have any docs yet](https://github.com/ts-rest/ts-rest/issues/554) and that the [linked example](https://github.com/ts-rest/ts-rest/blob/v3.40.0/apps/example-next/app/api/app-router/%5B...ts-rest%5D/route.ts) was very bare.
Basically what I'm trying to achieve is something like this:
The sample contract
```typescript
import { initContract } from '@ts-rest/core';
import { z } from 'zod';
const c = initContract();
export const contract = c.router({
hello: {
greet: { …
```

fix: ts error when using the tsr utility on createNextHandler

---

.changeset/twelve-ghosts-eat.md
libs/ts-rest/core/src/lib/dsl.spec.ts
libs/ts-rest/core/src/lib/dsl.ts

In our project, we need a mechanism to set metadata for a whole router (and for a sub-router, of course).
Then routes inside a router can inherit this metadata.
Use case:
- A router sets metadata with:
```
{
requireAuth: true
}
```
- Then all routes inside the router will have `requireAuth: true` along with their own metadata.

feat (ts-rest/core): allow merging router metadata to route metadata

---

libs/ts-rest/express/package.json
libs/ts-rest/fastify/package.json
libs/ts-rest/next/package.json
libs/ts-rest/open-api/package.json
libs/ts-rest/serverless/package.json

[ORT (OSS Review Toolkit)](https://oss-review-toolkit.org/ort/) compliance scanner fails because npm package: ts-rest:next:3.45.2 do not contain any license information

fix: Add License

---

.changeset/metal-pumpkins-grin.md
libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts

Hi, I want to be able to access route `metadata` within Fastify Route's config object so that I can do authorization in global plugin/middleware that reads permission data per route. Could you please consider this PR? The change is very simple.
cc: @oliverbutler

Add ts-rest metadata to Fastify Route Config

---

libs/ts-rest/express/src/index.ts
libs/ts-rest/express/src/lib/types.ts

We have a use case where we're working with the specific subtypes of `AppRouteImplementation`, and would benefit from these types being exported directly. Since the outer `AppRouteImplementation` is already exported, it seemed reasonable to export its composite parts as well.

feat: Expose subtypes of `AppRouteImplementation`.

---

apps/docs/docs/core/custom.md

Minor copy-pasta error in the docs, `response` isn't defined.
It might need a cast like the `Method` above, 🤷

docs: fix custom http client examples

---

apps/example-next/app/api/app-router/[...ts-rest]/route.ts

Without `export { handler as  OPTIONS }`, `ts-rest` will not be able to handle `OPTIONS` requests, and as such will e.g. not set CORS even if enabled.

fix: add OPTIONS export to nextjs app router example

---

.changeset/green-pots-laugh.md
libs/ts-rest/core/package.json
libs/ts-rest/core/src/lib/client.spec.ts
libs/ts-rest/core/src/lib/client.ts
libs/ts-rest/core/src/lib/infer-types.spec.ts
libs/ts-rest/core/src/lib/infer-types.ts
libs/ts-rest/core/tsconfig.spec.json
libs/ts-rest/next/src/lib/next-client.spec.ts
pnpm-lock.yaml

fix(core): fix broken types in node + ts 5.5 when `lib.dom` is not included

---

.github/workflows/build-test.yml

Move from 0.14 to 0.15 https://github.com/nrwl/ci/releases
seems we're hitting a deprecation _error_ from GH now

ci: move from 0.14 to 0.15 for nx cloud ci

---

.changeset/odd-cooks-leave.md
apps/example-express/src/authenticated-app.ts
libs/example-contracts/src/lib/contract-blog.ts
libs/ts-rest/express/src/lib/types.ts
libs/ts-rest/react-query-v5/src/v5/types/common.ts

Fixes #712.
This is mainly a fix for the typing system and does not break existing tests which was run with `pnpm nx affected:test`.

fix: AppRouteDeleteNoBody  should resolve to AppRouteQueryImplementation type

---

.changeset/long-crews-own.md
libs/ts-rest/react-query-v5/package.json

Bumps the peer dependency of the react-query-v5 package to react 19. 
Closes https://github.com/ts-rest/ts-rest/issues/731

chore: bump react peer dependency

---

pnpm-lock.yaml

Too eager on https://github.com/ts-rest/ts-rest/pull/732, missing lock file update.

fix: lock file outdated

---

.changeset/twenty-fans-reflect.md
libs/ts-rest/open-api/src/lib/ts-rest-open-api.spec.ts
libs/ts-rest/open-api/src/lib/ts-rest-open-api.ts

Fixes #366
By using `@anatine/zod-openapi` and setting the title property of a zod object, we can extract the schemas into `components` and reuse them around the code.
This will greatly reduce the output size of big APIs as well as generate much more compact SDKs automatically.
It assumes titles will be unique, and in case they are not, an exception will be thrown. We could use any other variable if you think it fits better.

Grouping schemas by title and referencing them on `@ts-rest/openapi`

---

apps/docs/docs/react-query/error-handling.md

The referenced function `isUndefinedErrorResponse` does not exist. It should be `isUnknownErrorReponse` instead.

docs: fix isUndefinedErrorResponse -> isUnknownErrorReponse

---

.changeset/shy-vans-float.md
apps/docs/docs/open-api.mdx
libs/ts-rest/open-api/src/lib/ts-rest-open-api.spec.ts
libs/ts-rest/open-api/src/lib/ts-rest-open-api.ts

This pull request updates the `generateOpenApi` function in the `ts-rest-open-api` library to enhance its flexibility by adding an additional parameter to the `operationMapper` callback. The new parameter provides more context for mapping operations.
* Updated the `operationMapper` callback signature to include a new `id` parameter, allowing it to receive the `id` of the route being processed. (`libs/ts-rest/open-api/src/lib/ts-rest-open-api.ts`, [libs/ts-rest/open-api/src/lib/ts-rest-open-api.tsR284](diffhunk://#diff-393f1f67c72980bbf00be005d8b28a2e878a2d934467ffe9f50b749a66a89ab7R284))
* Modified the invocation of `operationMapper` to pass the `id` parameter from the `path` object, ensuring the callback has access to this additional context. …

fix(openapi): expose path id to operation mapper

---

.changeset/big-camels-complain.md
libs/ts-rest/core/src/lib/client.spec.ts
libs/ts-rest/core/src/lib/client.ts

Calling `await new Response().json()` will throw an `Unexpected end of JSON input`. To prevent this issue from occurring on APIs that include the `Content-Type: application/json` header I've added a check to skip calling `response.json()` when the contract defines the status code as no body.

fix(client): prevent unexpected end of json

---

.changeset/plenty-seahorses-wait.md
libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts

I'm making this change so that I can support creating multiple route files and keep them typed. The AppRouteImplementation is already being [exported in the @ts-rest/express package](https://github.com/ts-rest/ts-rest/blob/fee9fbf348cce38b83e2450d5ac0b033dd13abd1/libs/ts-rest/express/src/lib/types.ts#L38-L43) so this is just mimicking that functionality.
Intended use-case example ([adapted from the Usage example for Fastify](https://ts-rest.com/docs/fastify#usage)):
```
import Fastify from 'fastify'
import { initServer } from '@ts-rest/fastify'
import { getPost } from './routes/getPost.ts'
import { createPost } from './routes/createPost.ts'
const app = Fastify()
const s = initServer()
const router = s.router(contract, {
getPost,
createPost,
})
app.register(s.plugin(router))
const start = …
```

feat: Export Fastify AppRouteImplementation and AppRouteImplementationOrOptions types to allow typed, scalable router files

---

.changeset/rare-elephants-itch.md
libs/ts-rest/next/src/lib/ts-rest-next.spec.ts
libs/ts-rest/next/src/lib/ts-rest-next.ts

Currently, the final `urlChunks` item contains the query string, which prevents the route from being matched.
This PR changes the logic to omit any query params from the URL before splitting it.
fixes #697

fix: nextjs 404 when query params are in URL
